name: gh-pages

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            .bin
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Tools
        uses: cargo-bins/cargo-binstall@v1.12.7

      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build wasm app
        run: |
          cargo just build-wasm
        env:
          RUSTDOCFLAGS: "-D warnings"
      
      - name: Prepare output folder
        run: |
          mkdir -p target/www
          cp index.html target/www/
          cp favicon.ico target/www/
          cp -r pkg target/www/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/www

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
